cluster.name: codepasser-cluster
node.name: codepasser-node-1
node.master: true
node.data: true
#network.host: 0.0.0.0
network.bind_host: 0.0.0.0
network.publish_host: 172.16.20.121
http.port: 9201
http.cors.enabled: true
http.cors.allow-origin: "*"
transport.tcp.port: 9301
discovery.zen.ping.unicast.hosts: ["172.16.20.121:9301","172.16.20.121:9302","172.16.20.121:9303"]
discovery.zen.minimum_master_nodes: 2
bootstrap.memory_lock: false
bootstrap.system_call_filter: false
cluster.initial_master_nodes: ["codepasser-node-1","codepasser-node-2","codepasser-node-3"]
